apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pega-cassandra
  labels:
    app: cassandra
spec:
  storageClassName: azure-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce