apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: cassandra
    release: pega
  name: data-pega-cassandra-1
  namespace: pega-namespace
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: azure-storage
