apiVersion: v1
kind: PersistentVolume
metadata:
  name: pega-stream
  labels:
    app: pega-stream
spec:
  storageClassName: azure-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce